import { describe, expect, it, vi } from 'vitest';
import { releaseFixtures } from '../../../fixtures/releases.js';
import { IntegrationError } from './integrations/errors.js';
import type { TorrServerAdapter, TorrServerTorrent } from './integrations/torrserver.js';
import { PlaybackCoordinator, PlaybackError, playableFiles, sanitizeMetadata } from './playback.js';
import { ReleaseCache } from './release-ranking.js';

const base = new URL('http://torr.test:8090');
const torrent: TorrServerTorrent = { hash: 'hash', title: 'Movie', files: [{ id: 10, path: 'Episode 10.mkv', length: 10 }, { id: 2, path: 'Episode 2.mp4', length: 20 }, { id: 1, path: 'sample.mkv', length: 1 }, { id: 3, path: 'note.txt', length: 1 }] };
function adapter(overrides: Partial<TorrServerAdapter> = {}): TorrServerAdapter { return { async health() { return true; }, async add() { return torrent; }, async inspect() { return torrent; }, async list() { return [torrent]; }, streamUrl(hash, fileId, path) { return new URL(`/stream/${encodeURIComponent(path)}?link=${hash}&index=${fileId}&play`, base); }, playlistUrl(hash) { return new URL(`/playlist?hash=${hash}`, base); }, ...overrides }; }
function setup(custom = adapter()) { const cache = new ReleaseCache(); const id = cache.put(releaseFixtures[0]!); return { id, coordinator: new PlaybackCoordinator(cache, custom, base) }; }

describe('playback handoff', () => {
  it('submits once with sanitized metadata and returns naturally sorted playable files', async () => { const add = vi.fn(async (...args: Parameters<TorrServerAdapter['add']>) => { void args; return torrent; }); const { id, coordinator } = setup(adapter({ add })); const result = await coordinator.handoff(id); expect(add).toHaveBeenCalledTimes(1); expect(Array.from(add.mock.calls[0]?.[1] ?? '').every((character) => character.charCodeAt(0) >= 32)).toBe(true); expect(result.status).toBe('choose_file'); expect(result.files.map((file) => file.path)).toEqual(['Episode 2.mp4', 'Episode 10.mkv']); });
  it('handles a single file as ready and exposes Lampa-compatible stream and playlist links', async () => { const one = { ...torrent, files: [{ id: 1, path: 'movie.mkv', length: 10 }] }; const { id, coordinator } = setup(adapter({ async add() { return one; } })); const result = await coordinator.handoff(id); expect(result).toMatchObject({ status: 'ready', files: [{ streamUrl: expect.stringContaining('/stream/movie.mkv?link=hash&index=1&play'), playlistUrl: expect.stringContaining('/playlist?hash=hash') }] }); });
  it('rejects unknown, expired/tampered, and reused IDs before another add', async () => { const add = vi.fn(async () => torrent); const { id, coordinator } = setup(adapter({ add })); await expect(coordinator.handoff('tampered-id')).rejects.toMatchObject({ code: 'CHOICE_UNKNOWN' }); await coordinator.handoff(id); await expect(coordinator.handoff(id)).rejects.toMatchObject({ code: 'CHOICE_USED' }); expect(add).toHaveBeenCalledTimes(1); });
  it('reports no playable files', async () => { const none = { ...torrent, files: [{ id: 1, path: 'sample.mkv', length: 1 }, { id: 2, path: 'readme.txt', length: 1 }] }; const { id, coordinator } = setup(adapter({ async add() { return none; } })); await expect(coordinator.handoff(id)).rejects.toMatchObject({ code: 'NO_PLAYABLE_FILES' }); });
  it('maps add/inspect timeout and permits retry after timeout', async () => { let calls = 0; const custom = adapter({ async add() { calls += 1; if (calls === 1) throw new IntegrationError('UPSTREAM_TIMEOUT', 'timeout'); return torrent; } }); const { id, coordinator } = setup(custom); await expect(coordinator.handoff(id)).rejects.toMatchObject({ code: 'TORRSERVER_TIMEOUT' }); await expect(coordinator.handoff(id)).resolves.toMatchObject({ status: 'choose_file' }); });
  it('rejects unsafe stream origins and schemes', async () => { const { id, coordinator } = setup(adapter({ streamUrl() { return new URL('javascript:alert(1)'); } })); await expect(coordinator.handoff(id)).rejects.toMatchObject({ code: 'UNSAFE_STREAM_URL' }); expect(() => new PlaybackCoordinator(new ReleaseCache(), adapter(), new URL('ftp://torr.test'))).toThrow(PlaybackError); });
  it('expires playback sessions and releases used choice IDs', async () => { let now = 1000; const cache = new ReleaseCache(); const id = cache.put(releaseFixtures[0]!); const coordinator = new PlaybackCoordinator(cache, adapter(), base, 10, () => now); const session = await coordinator.handoff(id); expect(coordinator.getSession(session.sessionId)).not.toBeNull(); now = 2000; expect(coordinator.getSession(session.sessionId)).toBeNull(); await expect(coordinator.handoff(id)).resolves.toMatchObject({ status: 'choose_file' }); });
  it('sanitizes control characters and bounds metadata', () => { expect(sanitizeMetadata(`bad\u0000 title ${'x'.repeat(200)}`)).toHaveLength(160); expect(playableFiles(torrent.files)).toHaveLength(2); });
});
