plugins {
    id "com.android.application"
}

android {
    namespace "ru.kinohub.tv"
    compileSdk 35

    defaultConfig {
        applicationId "ru.kinohub.tv"
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName "0.3.0"
        buildConfigField "String", "KINOHUB_URL", '"http://192.168.0.120:4100/"'
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}
